import type { FormDefinition } from "$lib/components/dynamic-forms";

export const sampleFormDefinition: FormDefinition = {
	id: "sample-contact",
	name: "Contact Form",
	description: "A sample contact form demonstrating all field types",
	fields: [
		{
			id: "f1",
			name: "fullName",
			type: "text",
			label: "Full Name",
			placeholder: "John Doe",
			required: true,
			validation: { minLength: 2 },
			width: "full",
		},
		{
			id: "f2",
			name: "email",
			type: "email",
			label: "Email Address",
			placeholder: "john@example.com",
			required: true,
			width: "half",
		},
		{
			id: "f3",
			name: "phone",
			type: "phone",
			label: "Phone Number",
			placeholder: "+1 (555) 000-0000",
			width: "half",
		},
		{
			id: "f4",
			name: "department",
			type: "select",
			label: "Department",
			placeholder: "Select a department...",
			required: true,
			options: [
				{ label: "Engineering", value: "engineering" },
				{ label: "Design", value: "design" },
				{ label: "Marketing", value: "marketing" },
				{ label: "Sales", value: "sales" },
			],
			width: "half",
		},
		{
			id: "f5",
			name: "priority",
			type: "radio",
			label: "Priority",
			required: true,
			options: [
				{ label: "Low", value: "low" },
				{ label: "Medium", value: "medium" },
				{ label: "High", value: "high" },
			],
			width: "half",
		},
		{
			id: "f6",
			name: "message",
			type: "textarea",
			label: "Message",
			placeholder: "Tell us what you need...",
			required: true,
			validation: { minLength: 10, maxLength: 500 },
		},
		{
			id: "f7",
			name: "satisfaction",
			type: "slider",
			label: "Satisfaction Score",
			validation: { min: 0, max: 100, step: 5 },
			defaultValue: 50,
			width: "half",
		},
		{
			id: "f8",
			name: "tags",
			type: "tags",
			label: "Tags",
			placeholder: "Add relevant tags...",
			description: "Press Enter to add a tag",
			width: "half",
		},
		{
			id: "f9",
			name: "newsletter",
			type: "switch",
			label: "Subscribe to newsletter",
			description: "Get weekly updates about our products",
			width: "half",
		},
		{
			id: "f10",
			name: "termsAccepted",
			type: "checkbox",
			label: "I accept the terms and conditions",
			required: true,
			width: "half",
		},
	],
};
