import type { AuditLog } from "$lib/components/audit-log-viewer";

/**
 * A multi-entry audit trail for one fictional `person` record. Exercises:
 *   - `create` (no `before`)
 *   - several `update`s touching different fields (single-field, multi-field,
 *     a value being nulled out, a field being added later)
 *   - `delete` (no `after`) followed by an `update` that "restores" it, so the
 *     viewer's restoration / removal coloring both light up
 *
 * Snapshots are flat objects of primitive values, matching the v1 viewer model.
 */
export const sampleAuditLog: AuditLog = {
	recordId: "person-4218",
	recordType: "person",
	entries: [
		{
			id: "entry-1",
			recordId: "person-4218",
			recordType: "person",
			action: "create",
			changedAt: "2026-04-02T09:14:00Z",
			changedBy: { id: "u-101", name: "Marisol Reyes", email: "marisol@deebee.tech" },
			reason: "Imported from CSV upload (Q2 onboarding batch).",
			before: null,
			after: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: null,
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "lead",
				marketingOptIn: false,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "",
			},
		},
		{
			id: "entry-2",
			recordId: "person-4218",
			recordType: "person",
			action: "update",
			changedAt: "2026-04-05T15:42:30Z",
			changedBy: { id: "u-204", name: "Daniel Park", email: "daniel@deebee.tech" },
			reason: "Phone number captured during welcome call.",
			before: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: null,
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "lead",
				marketingOptIn: false,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "",
			},
			after: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: "+1-503-555-0142",
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "lead",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "",
			},
		},
		{
			id: "entry-3",
			recordId: "person-4218",
			recordType: "person",
			action: "update",
			changedAt: "2026-04-08T11:05:12Z",
			changedBy: { id: "u-101", name: "Marisol Reyes", email: "marisol@deebee.tech" },
			reason: "Promoted to MQL after webinar attendance.",
			before: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: "+1-503-555-0142",
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "lead",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "",
			},
			after: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: "+1-503-555-0142",
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "mql",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "Attended Q2 product webinar; interested in Pro tier.",
				leadScore: 42,
			},
		},
		{
			id: "entry-4",
			recordId: "person-4218",
			recordType: "person",
			action: "update",
			changedAt: "2026-04-12T08:30:00Z",
			changedBy: { id: "u-307", name: "Hannah Olsen", email: "hannah@deebee.tech" },
			reason: "Customer correction: legal name + relocation.",
			before: {
				firstName: "Avery",
				lastName: "Nguyen",
				email: "avery.nguyen@example.com",
				phone: "+1-503-555-0142",
				city: "Portland",
				state: "OR",
				role: "Subscriber",
				lifecycleStage: "mql",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "Attended Q2 product webinar; interested in Pro tier.",
				leadScore: 42,
			},
			after: {
				firstName: "Avery Jordan",
				lastName: "Nguyen-Pérez",
				email: "avery.j.nguyen@example.com",
				phone: "+1-206-555-0188",
				city: "Seattle",
				state: "WA",
				role: "Subscriber",
				lifecycleStage: "mql",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "Attended Q2 product webinar; interested in Pro tier.",
				leadScore: 58,
			},
		},
		{
			id: "entry-5",
			recordId: "person-4218",
			recordType: "person",
			action: "update",
			changedAt: "2026-04-16T17:55:09Z",
			changedBy: { id: "u-204", name: "Daniel Park", email: "daniel@deebee.tech" },
			reason: "Closed first deal — promoted to customer.",
			before: {
				firstName: "Avery Jordan",
				lastName: "Nguyen-Pérez",
				email: "avery.j.nguyen@example.com",
				phone: "+1-206-555-0188",
				city: "Seattle",
				state: "WA",
				role: "Subscriber",
				lifecycleStage: "mql",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 0,
				notes: "Attended Q2 product webinar; interested in Pro tier.",
				leadScore: 58,
			},
			after: {
				firstName: "Avery Jordan",
				lastName: "Nguyen-Pérez",
				email: "avery.j.nguyen@example.com",
				phone: "+1-206-555-0188",
				city: "Seattle",
				state: "WA",
				role: "Customer",
				lifecycleStage: "customer",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 1499,
				notes: null,
				leadScore: 58,
				accountTier: "Pro",
			},
		},
		{
			id: "entry-6",
			recordId: "person-4218",
			recordType: "person",
			action: "delete",
			changedAt: "2026-04-19T10:11:42Z",
			changedBy: { id: "u-999", name: "System (GDPR job)", email: "system@deebee.tech" },
			reason: "GDPR right-to-erasure request received.",
			before: {
				firstName: "Avery Jordan",
				lastName: "Nguyen-Pérez",
				email: "avery.j.nguyen@example.com",
				phone: "+1-206-555-0188",
				city: "Seattle",
				state: "WA",
				role: "Customer",
				lifecycleStage: "customer",
				marketingOptIn: true,
				signupDate: "2026-04-02",
				lifetimeValue: 1499,
				notes: null,
				leadScore: 58,
				accountTier: "Pro",
			},
			after: null,
		},
	],
};
