/**
 * Curated set of Lucide icon names for the step icon quick-pick UI.
 * Any valid Lucide icon name can be used in a step definition;
 * this list just provides convenient browsing in the builder.
 */
export const STEP_ICON_QUICK_PICKS: { name: string; label: string }[] = [
	{ name: "user", label: "User" },
	{ name: "users", label: "Users" },
	{ name: "mail", label: "Email" },
	{ name: "phone", label: "Phone" },
	{ name: "graduation-cap", label: "Education" },
	{ name: "map-pin", label: "Location" },
	{ name: "globe", label: "Globe" },
	{ name: "house", label: "Home" },
	{ name: "building-2", label: "Building" },
	{ name: "briefcase", label: "Briefcase" },
	{ name: "credit-card", label: "Payment" },
	{ name: "wallet", label: "Wallet" },
	{ name: "package", label: "Package" },
	{ name: "truck", label: "Shipping" },
	{ name: "shield", label: "Shield" },
	{ name: "lock", label: "Lock" },
	{ name: "key", label: "Key" },
	{ name: "settings", label: "Settings" },
	{ name: "sliders-horizontal", label: "Preferences" },
	{ name: "file-text", label: "Document" },
	{ name: "clipboard-list", label: "Clipboard" },
	{ name: "folder", label: "Folder" },
	{ name: "image", label: "Image" },
	{ name: "camera", label: "Camera" },
	{ name: "upload", label: "Upload" },
	{ name: "calendar", label: "Calendar" },
	{ name: "clock", label: "Clock" },
	{ name: "heart", label: "Heart" },
	{ name: "star", label: "Star" },
	{ name: "bookmark", label: "Bookmark" },
	{ name: "bell", label: "Notification" },
	{ name: "info", label: "Info" },
	{ name: "circle-question-mark", label: "Help" },
	{ name: "triangle-alert", label: "Warning" },
	{ name: "circle-check-big", label: "Complete" },
	{ name: "list-checks", label: "Checklist" },
	{ name: "pencil", label: "Edit" },
	{ name: "search", label: "Search" },
	{ name: "link", label: "Link" },
	{ name: "database", label: "Database" },
	{ name: "chart-column", label: "Analytics" },
];
