import type { FormDefinition } from "$lib/components/dynamic-forms";

export const sampleMultistepDefinition: FormDefinition = {
	id: "sample-onboarding",
	name: "Employee Onboarding",
	description: "Multi-step onboarding form for new employees",
	fields: [],
	steps: [
		{
			id: "step-personal",
			title: "Personal Info",
			description: "Basic personal details",
			icon: "user",
			fields: [
				{
					id: "ms-f1",
					name: "firstName",
					type: "text",
					label: "First Name",
					placeholder: "Jane",
					required: true,
					validation: { minLength: 2 },
					width: "half",
				},
				{
					id: "ms-f2",
					name: "lastName",
					type: "text",
					label: "Last Name",
					placeholder: "Smith",
					required: true,
					validation: { minLength: 2 },
					width: "half",
				},
				{
					id: "ms-f3",
					name: "email",
					type: "email",
					label: "Email Address",
					placeholder: "jane.smith@company.com",
					required: true,
					width: "half",
				},
				{
					id: "ms-f4",
					name: "phone",
					type: "phone",
					label: "Phone Number",
					placeholder: "+1 (555) 000-0000",
					width: "half",
				},
				{
					id: "ms-f5",
					name: "dateOfBirth",
					type: "date",
					label: "Date of Birth",
					width: "half",
				},
			],
		},
		{
			id: "step-job",
			title: "Job Details",
			description: "Role and department information",
			icon: "briefcase",
			fields: [
				{
					id: "ms-f6",
					name: "department",
					type: "select",
					label: "Department",
					placeholder: "Select a department...",
					required: true,
					options: [
						{ label: "Engineering", value: "engineering" },
						{ label: "Design", value: "design" },
						{ label: "Marketing", value: "marketing" },
						{ label: "Sales", value: "sales" },
						{ label: "HR", value: "hr" },
					],
					width: "half",
				},
				{
					id: "ms-f7",
					name: "jobTitle",
					type: "text",
					label: "Job Title",
					placeholder: "e.g. Senior Engineer",
					required: true,
					width: "half",
				},
				{
					id: "ms-f8",
					name: "employmentType",
					type: "radio",
					label: "Employment Type",
					required: true,
					options: [
						{ label: "Full-time", value: "full-time" },
						{ label: "Part-time", value: "part-time" },
						{ label: "Contract", value: "contract" },
					],
					width: "half",
				},
				{
					id: "ms-f9",
					name: "skills",
					type: "tags",
					label: "Skills",
					placeholder: "Add relevant skills...",
					description: "Press Enter to add a skill",
					width: "half",
				},
			],
		},
		{
			id: "step-preferences",
			title: "Preferences",
			description: "Work preferences and agreements",
			icon: "sliders-horizontal",
			fields: [
				{
					id: "ms-f10",
					name: "bio",
					type: "textarea",
					label: "Short Bio",
					placeholder: "Tell us about yourself...",
					validation: { maxLength: 300 },
				},
				{
					id: "ms-f11",
					name: "newsletter",
					type: "switch",
					label: "Subscribe to company newsletter",
					description: "Get weekly updates about company events",
					width: "half",
				},
				{
					id: "ms-f12",
					name: "acceptTerms",
					type: "checkbox",
					label: "I accept the terms and conditions",
					required: true,
					width: "half",
				},
			],
		},
	],
};
